scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile77`, function (sprite, location) {
    game.reset()
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile79`, function (sprite, location) {
    game.reset()
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile94`, function (sprite, location) {
    tiles.setTilemap(tilemap`level1`)
    mySprite = sprites.create(img`
        ....................
        ....................
        ....................
        ....................
        ....................
        ......cccc.cccc.....
        .....cc44ccc44cc....
        ....cc4444c4444cc...
        ....cc444444444cc...
        ....cc444444444cc...
        .....cc4444444cc....
        ......cc44444cc.....
        .......cc444cc......
        ........cc4cc.......
        .........ccc........
        ..........c.........
        ....................
        ....................
        ....................
        ....................
        `, SpriteKind.Player)
    controller.moveSprite(mySprite)
    scene.cameraFollowSprite(mySprite)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile58`, function (sprite, location) {
    tiles.setTilemap(tilemap`level7`)
    mySprite = sprites.create(img`
        ....................
        ....................
        ....................
        ....................
        ....................
        ......cccc.cccc.....
        .....cc44ccc44cc....
        ....cc4444c4444cc...
        ....cc444444444cc...
        ....cc444444444cc...
        .....cc4444444cc....
        ......cc44444cc.....
        .......cc444cc......
        ........cc4cc.......
        .........ccc........
        ..........c.........
        ....................
        ....................
        ....................
        ....................
        `, SpriteKind.Player)
    controller.moveSprite(mySprite)
    scene.cameraFollowSprite(mySprite)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile45`, function (sprite, location) {
    game.reset()
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile15`, function (sprite, location) {
    game.reset()
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile46`, function (sprite, location) {
    game.reset()
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile42`, function (sprite, location) {
    game.reset()
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile39`, function (sprite, location) {
    game.reset()
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.tilePath9, function (sprite, location) {
    game.over(true)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile16`, function (sprite, location) {
    game.reset()
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile40`, function (sprite, location) {
    game.reset()
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile36`, function (sprite, location) {
    game.reset()
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile59`, function (sprite, location) {
    tiles.setTilemap(tilemap`level7`)
    mySprite = sprites.create(img`
        ....................
        ....................
        ....................
        ....................
        ....................
        ......cccc.cccc.....
        .....cc44ccc44cc....
        ....cc4444c4444cc...
        ....cc444444444cc...
        ....cc444444444cc...
        .....cc4444444cc....
        ......cc44444cc.....
        .......cc444cc......
        ........cc4cc.......
        .........ccc........
        ..........c.........
        ....................
        ....................
        ....................
        ....................
        `, SpriteKind.Player)
    controller.moveSprite(mySprite)
    scene.cameraFollowSprite(mySprite)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile44`, function (sprite, location) {
    game.reset()
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.tilePath3, function (sprite, location) {
    game.over(true)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile100`, function (sprite, location) {
    tiles.setTilemap(tilemap`level25`)
    mySprite = sprites.create(img`
        ....................
        ....................
        ....................
        ....................
        ....................
        ......cccc.cccc.....
        .....cc44ccc44cc....
        ....cc4444c4444cc...
        ....cc444444444cc...
        ....cc444444444cc...
        .....cc4444444cc....
        ......cc44444cc.....
        .......cc444cc......
        ........cc4cc.......
        .........ccc........
        ..........c.........
        ....................
        ....................
        ....................
        ....................
        `, SpriteKind.Player)
    controller.moveSprite(mySprite)
    scene.cameraFollowSprite(mySprite)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile43`, function (sprite, location) {
    game.reset()
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile93`, function (sprite, location) {
    tiles.setTilemap(tilemap`level1`)
    mySprite = sprites.create(img`
        ....................
        ....................
        ....................
        ....................
        ....................
        ......cccc.cccc.....
        .....cc44ccc44cc....
        ....cc4444c4444cc...
        ....cc444444444cc...
        ....cc444444444cc...
        .....cc4444444cc....
        ......cc44444cc.....
        .......cc444cc......
        ........cc4cc.......
        .........ccc........
        ..........c.........
        ....................
        ....................
        ....................
        ....................
        `, SpriteKind.Player)
    controller.moveSprite(mySprite)
    scene.cameraFollowSprite(mySprite)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile61`, function (sprite, location) {
    tiles.setTilemap(tilemap`level7`)
    mySprite = sprites.create(img`
        ....................
        ....................
        ....................
        ....................
        ....................
        ......cccc.cccc.....
        .....cc44ccc44cc....
        ....cc4444c4444cc...
        ....cc444444444cc...
        ....cc444444444cc...
        .....cc4444444cc....
        ......cc44444cc.....
        .......cc444cc......
        ........cc4cc.......
        .........ccc........
        ..........c.........
        ....................
        ....................
        ....................
        ....................
        `, SpriteKind.Player)
    controller.moveSprite(mySprite)
    scene.cameraFollowSprite(mySprite)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile62`, function (sprite, location) {
    tiles.setTilemap(tilemap`level7`)
    mySprite = sprites.create(img`
        ....................
        ....................
        ....................
        ....................
        ....................
        ......cccc.cccc.....
        .....cc44ccc44cc....
        ....cc4444c4444cc...
        ....cc444444444cc...
        ....cc444444444cc...
        .....cc4444444cc....
        ......cc44444cc.....
        .......cc444cc......
        ........cc4cc.......
        .........ccc........
        ..........c.........
        ....................
        ....................
        ....................
        ....................
        `, SpriteKind.Player)
    controller.moveSprite(mySprite)
    scene.cameraFollowSprite(mySprite)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile31`, function (sprite, location) {
    game.reset()
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile41`, function (sprite, location) {
    game.reset()
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile99`, function (sprite, location) {
    tiles.setTilemap(tilemap`level25`)
    mySprite = sprites.create(img`
        ....................
        ....................
        ....................
        ....................
        ....................
        ......cccc.cccc.....
        .....cc44ccc44cc....
        ....cc4444c4444cc...
        ....cc444444444cc...
        ....cc444444444cc...
        .....cc4444444cc....
        ......cc44444cc.....
        .......cc444cc......
        ........cc4cc.......
        .........ccc........
        ..........c.........
        ....................
        ....................
        ....................
        ....................
        `, SpriteKind.Player)
    scene.cameraFollowSprite(mySprite)
    controller.moveSprite(mySprite)
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.tilePath6, function (sprite, location) {
    game.over(true)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile35`, function (sprite, location) {
    game.reset()
    info.changeLifeBy(-1)
})
let mySprite: Sprite = null
tiles.placeOnRandomTile(mySprite, assets.tile`myTile98`)
scene.setBackgroundImage(assets.image`Background`)
mySprite = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ......cccc.cccc.....
    .....cc44ccc44cc....
    ....cc4444c4444cc...
    ....cc444444444cc...
    ....cc444444444cc...
    .....cc4444444cc....
    ......cc44444cc.....
    .......cc444cc......
    ........cc4cc.......
    .........ccc........
    ..........c.........
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
tiles.setTilemap(tilemap`level13`)
scene.cameraFollowSprite(mySprite)
forever(function () {
    info.setLife(9)
})
